// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Stylophone.iOS.Views
{
	public partial class SymbolUIButton : UIButton
	{
		public SymbolUIButton (IntPtr handle) : base (handle)
		{
			
		}

		public override void AwakeFromNib()
        {
            // https://stackoverflow.com/questions/58338420/sf-symbol-looks-distorted
            ImageView.ContentMode = UIViewContentMode.ScaleAspectFit;
        }
    }
}
