// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using Microsoft.Toolkit.Mvvm.DependencyInjection;
using Strings = Stylophone.Localization.Strings.Resources;
using Stylophone.Common.ViewModels;
using Stylophone.iOS.Helpers;
using UIKit;
using CoreGraphics;
using SkiaSharp.Views.iOS;
using System.ComponentModel;
using SkiaSharp;

namespace Stylophone.iOS.ViewControllers
{
	public partial class AlbumDetailViewController : UITableViewController, IViewController<AlbumDetailViewModel>
	{
		public AlbumDetailViewController (IntPtr handle) : base (handle)
		{
		}

		public AlbumDetailViewModel ViewModel => Ioc.Default.GetRequiredService<AlbumDetailViewModel>();
		public PropertyBinder<AlbumDetailViewModel> Binder => new(ViewModel);

		private PropertyBinder<AlbumViewModel> _albumBinder;
		private UIBarButtonItem _settingsBtn;

		public override void AwakeFromNib()
		{
			base.AwakeFromNib();
			TraitCollectionDidChange(null);
			NavigationItem.LargeTitleDisplayMode = UINavigationItemLargeTitleDisplayMode.Never;
			
			var trackDataSource = new TrackTableViewDataSource(TableView, ViewModel.Source, GetRowContextMenu, GetRowSwipeActions, true, OnScroll);
			TableView.DataSource = trackDataSource;
			TableView.Delegate = trackDataSource;

			Binder.Bind<bool>(EmptyView, "hidden", nameof(ViewModel.IsSourceEmpty),
				valueTransformer: NSValueTransformer.GetValueTransformer(nameof(ReverseBoolValueTransformer)));
			Binder.Bind<string>(AlbumTrackInfo, "text", nameof(ViewModel.PlaylistInfo));
		}

		private void OnScroll(UIScrollView scrollView)
        {
            if (scrollView.ContentOffset.Y > 192)
            {
				Title = ViewModel?.Item.Name;
				NavigationItem.RightBarButtonItem = _settingsBtn;
			}	
			else
            {
				Title = "";
				NavigationItem.RightBarButtonItem = null;
			}
		}

        public override void TraitCollectionDidChange(UITraitCollection previousTraitCollection)
        {
            base.TraitCollectionDidChange(previousTraitCollection);

			var headerView = TableView.TableHeaderView;
			CGRect newFrame = headerView.Frame;
			if (TraitCollection.VerticalSizeClass == UIUserInterfaceSizeClass.Compact)
			{
				newFrame.Height = 242;
			}
			else
			{
				newFrame.Height = 296;
			}
			headerView.Frame = newFrame;
			TableView.TableHeaderView = headerView;
		}

		void IPreparableViewController.Prepare(object parameter)
        {
			TableView.ScrollRectToVisible(new CGRect(0, 0, 1, 1), false);

			var album = parameter as AlbumViewModel;
			ViewModel.Initialize(album);

			// Reset label texts
			AlbumArtists.Text = "...";

			// Rebindall to our new album VM
			_albumBinder?.Dispose();
			_albumBinder = new PropertyBinder<AlbumViewModel>(ViewModel.Item);

			_albumBinder.Bind<string>(AlbumTitle, "text", nameof(album.Name));
			_albumBinder.Bind<string>(AlbumArtists, "text", nameof(album.Artist));
			_albumBinder.Bind<bool>(AlbumArtLoadingIndicator, "animating", nameof(album.AlbumArtLoaded),
				valueTransformer: NSValueTransformer.GetValueTransformer(nameof(ReverseBoolValueTransformer)));

			_albumBinder.BindButton(PlayButton, Strings.ContextMenuPlay, album.PlayAlbumCommand);
			PlayButton.Layer.CornerRadius = 8;
			_albumBinder.BindButton(AddToQueueButton, Strings.ContextMenuAddToQueue, album.AddAlbumCommand);
			AddToQueueButton.Layer.CornerRadius = 8;
			_albumBinder.BindButton(PlaylistButton, Strings.ContextMenuAddToPlaylist, album.AddToPlaylistCommand);
			PlaylistButton.Layer.CornerRadius = 8;

			_settingsBtn = CreateSettingsButton();

			var imageConverter = NSValueTransformer.GetValueTransformer(nameof(SkiaToUIImageValueTransformer));
			var colorConverter = NSValueTransformer.GetValueTransformer(nameof(SkiaToUIColorValueTransformer));

			_albumBinder.Bind<SKImage>(AlbumArt, "image", nameof(album.AlbumArt), valueTransformer: imageConverter);
			_albumBinder.Bind<SKImage>(BackgroundArt, "image", nameof(album.AlbumArt), valueTransformer: imageConverter);
			_albumBinder.Bind<SKColor>(PlayButton, "backgroundColor", nameof(album.DominantColor), valueTransformer: colorConverter);
			_albumBinder.Bind<SKColor>(AddToQueueButton, "backgroundColor", nameof(album.DominantColor), valueTransformer: colorConverter);
			_albumBinder.Bind<SKColor>(PlaylistButton, "backgroundColor", nameof(album.DominantColor), valueTransformer: colorConverter);

			// Add radius to AlbumArt
			AlbumArt.Layer.CornerRadius = 8;
			AlbumArt.Layer.MasksToBounds = true;

			ArtContainer.Layer.ShadowColor = UIColor.Black.CGColor;
			ArtContainer.Layer.ShadowOpacity = 0.5F;
			ArtContainer.Layer.ShadowOffset = new CGSize(0, 0);
			ArtContainer.Layer.ShadowRadius = 4;
		}

        private UIMenu GetRowContextMenu(NSIndexPath indexPath)
		{
			// The common commands take a list of objects
			var trackList = new List<object>();

			if (TableView.IndexPathsForSelectedRows == null)
			{
				trackList.Add(ViewModel?.Source[indexPath.Row]);
			}
			else
			{
				trackList = TableView.IndexPathsForSelectedRows.Select(indexPath => ViewModel?.Source[indexPath.Row])
				.ToList<object>();
			}

			var queueAction = Binder.GetCommandAction(Strings.ContextMenuAddToQueue, "plus", ViewModel.AddToQueueCommand, trackList);
			var playlistAction = Binder.GetCommandAction(Strings.ContextMenuAddToPlaylist, "music.note.list", ViewModel.AddToPlayListCommand, trackList);

			return UIMenu.Create(new[] { queueAction, playlistAction });
		}

		private UISwipeActionsConfiguration GetRowSwipeActions(NSIndexPath indexPath, bool isLeadingSwipe)
		{
			// The common commands take a list of objects
			var trackList = new List<object>();
			trackList.Add(ViewModel?.Source[indexPath.Row]);

			var action = isLeadingSwipe ? Binder.GetContextualAction(UIContextualActionStyle.Normal, Strings.ContextMenuAddToQueue, ViewModel.AddToQueueCommand, trackList)
				: Binder.GetContextualAction(UIContextualActionStyle.Normal, Strings.ContextMenuAddToPlaylist, ViewModel.AddToPlayListCommand, trackList);

			return UISwipeActionsConfiguration.FromActions(new[] { action });
		}

		private UIBarButtonItem CreateSettingsButton()
		{
			var playAlbumAction = Binder.GetCommandAction(Strings.ContextMenuPlay, "play", ViewModel.Item.PlayAlbumCommand);
			var addAlbumAction = Binder.GetCommandAction(Strings.ContextMenuAddToQueue, "plus", ViewModel.Item.AddAlbumCommand);
			var addToPlaylistAction = Binder.GetCommandAction(Strings.ContextMenuAddToPlaylist, "music.note.list", ViewModel.Item.AddToPlaylistCommand);

			var barButtonMenu = UIMenu.Create(new[] { playAlbumAction, addAlbumAction, addToPlaylistAction });
			return new UIBarButtonItem(UIImage.GetSystemImage("ellipsis.circle"), barButtonMenu);
		}
	}
}
