// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Stylophone.Common.ViewModels;
using UIKit;

namespace Stylophone.iOS.ViewControllers
{
	public partial class FilePathCell : UICollectionViewCell
	{
		public FilePathCell (IntPtr handle) : base (handle)
		{
		}

		internal void Initialize(FilePathViewModel viewModel, bool isBackItem = false)
        {
			if (isBackItem)
			{
				FilePathImage.Image = UIImage.GetSystemImage("arrowshape.turn.up.backward.fill");
				FilePathLabel.Text = "..";
				return;
			}

			FilePathImage.Image = viewModel.IsDirectory ? UIImage.GetSystemImage("folder.fill") : UIImage.GetSystemImage("music.note");
            FilePathLabel.Text = viewModel.Name;
        }
    }
}
