//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylophone.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stylophone.Localization.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Volume.
        /// </summary>
        public static string ActionChangeVolume {
            get {
                return ResourceManager.GetString("ActionChangeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mini Player.
        /// </summary>
        public static string ActionCompactOverlay {
            get {
                return ResourceManager.GetString("ActionCompactOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Fullscreen Playback.
        /// </summary>
        public static string ActionFullscreenPlayback {
            get {
                return ResourceManager.GetString("ActionFullscreenPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Actions.
        /// </summary>
        public static string ActionMore {
            get {
                return ResourceManager.GetString("ActionMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string ActionPlayPause {
            get {
                return ResourceManager.GetString("ActionPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Track.
        /// </summary>
        public static string ActionSkipNext {
            get {
                return ResourceManager.GetString("ActionSkipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Track.
        /// </summary>
        public static string ActionSkipPrevious {
            get {
                return ResourceManager.GetString("ActionSkipPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Consume.
        /// </summary>
        public static string ActionToggleConsume {
            get {
                return ResourceManager.GetString("ActionToggleConsume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Repeat.
        /// </summary>
        public static string ActionToggleRepeat {
            get {
                return ResourceManager.GetString("ActionToggleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Shuffle.
        /// </summary>
        public static string ActionToggleShuffle {
            get {
                return ResourceManager.GetString("ActionToggleShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Playlist.
        /// </summary>
        public static string AddToPlaylistCreateNewPlaylist {
            get {
                return ResourceManager.GetString("AddToPlaylistCreateNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist Name.
        /// </summary>
        public static string AddToPlaylistNewPlaylistName {
            get {
                return ResourceManager.GetString("AddToPlaylistNewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Playlist.
        /// </summary>
        public static string AddToPlaylistPlaceholder {
            get {
                return ResourceManager.GetString("AddToPlaylistPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddToPlaylistPrimaryButtonText {
            get {
                return ResourceManager.GetString("AddToPlaylistPrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add track(s) to the following Playlist:.
        /// </summary>
        public static string AddToPlaylistText {
            get {
                return ResourceManager.GetString("AddToPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        public static string AddToPlaylistTitle {
            get {
                return ResourceManager.GetString("AddToPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylophone.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Queue as Playlist.
        /// </summary>
        public static string ContextMenuAddQueueToPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuAddQueueToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Playlist.
        /// </summary>
        public static string ContextMenuAddToPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to Queue.
        /// </summary>
        public static string ContextMenuAddToQueue {
            get {
                return ResourceManager.GetString("ContextMenuAddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Queue.
        /// </summary>
        public static string ContextMenuClearQueue {
            get {
                return ResourceManager.GetString("ContextMenuClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Playlist.
        /// </summary>
        public static string ContextMenuDeletePlaylist {
            get {
                return ResourceManager.GetString("ContextMenuDeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string ContextMenuPlay {
            get {
                return ResourceManager.GetString("ContextMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Playlist.
        /// </summary>
        public static string ContextMenuRemoveFromPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuRemoveFromPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Queue.
        /// </summary>
        public static string ContextMenuRemoveFromQueue {
            get {
                return ResourceManager.GetString("ContextMenuRemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Album.
        /// </summary>
        public static string ContextMenuViewAlbum {
            get {
                return ResourceManager.GetString("ContextMenuViewAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Database is Updating.
        /// </summary>
        public static string DatabaseUpdateHeader {
            get {
                return ResourceManager.GetString("DatabaseUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Playlist?.
        /// </summary>
        public static string DeletePlaylistContentDialog {
            get {
                return ResourceManager.GetString("DeletePlaylistContentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is your MPD server connected?.
        /// </summary>
        public static string EmptyFoldersDesc {
            get {
                return ResourceManager.GetString("EmptyFoldersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No folders found on server..
        /// </summary>
        public static string EmptyFoldersTitle {
            get {
                return ResourceManager.GetString("EmptyFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ain&apos;t nothin&apos; like an empty library..
        /// </summary>
        public static string EmptyLibraryTitle {
            get {
                return ResourceManager.GetString("EmptyLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get some tracks in there!.
        /// </summary>
        public static string EmptyPlaylistDesc {
            get {
                return ResourceManager.GetString("EmptyPlaylistDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can&apos;t jam to this..
        /// </summary>
        public static string EmptyPlaylistTitle {
            get {
                return ResourceManager.GetString("EmptyPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why don&apos;t you add some music?.
        /// </summary>
        public static string EmptyQueueDesc {
            get {
                return ResourceManager.GetString("EmptyQueueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All is quiet now..
        /// </summary>
        public static string EmptyQueueTitle {
            get {
                return ResourceManager.GetString("EmptyQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Tracks found on Server..
        /// </summary>
        public static string EmptySearchDesc {
            get {
                return ResourceManager.GetString("EmptySearchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funky Fresh Search!.
        /// </summary>
        public static string EmptySearchTitle {
            get {
                return ResourceManager.GetString("EmptySearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add Album: {0}.
        /// </summary>
        public static string ErrorAddingAlbum {
            get {
                return ResourceManager.GetString("ErrorAddingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t clear queue!.
        /// </summary>
        public static string ErrorCantClearCache {
            get {
                return ResourceManager.GetString("ErrorCantClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MPD Response..
        /// </summary>
        public static string ErrorInvalidMPDResponse {
            get {
                return ResourceManager.GetString("ErrorInvalidMPDResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This track doesn&apos;t have a matching Album..
        /// </summary>
        public static string ErrorNoMatchingAlbum {
            get {
                return ResourceManager.GetString("ErrorNoMatchingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error trying to play the MPD server&apos;s httpd stream.
        /// </summary>
        public static string ErrorPlayingMPDStream {
            get {
                return ResourceManager.GetString("ErrorPlayingMPDStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t play content: {0}.
        /// </summary>
        public static string ErrorPlayingTrack {
            get {
                return ResourceManager.GetString("ErrorPlayingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending {0} failed.
        /// </summary>
        public static string ErrorSendingMPDCommand {
            get {
                return ResourceManager.GetString("ErrorSendingMPDCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Playlists failed.
        /// </summary>
        public static string ErrorUpdatingPlaylist {
            get {
                return ResourceManager.GetString("ErrorUpdatingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Bowie is credited with playing the Stylophone on his 1969 debut hit song &quot;Space Oddity&quot; and also for his 2002 album Heathen track titled &quot;Slip Away,&quot; as well as on the song &quot;Heathen (The Rays)&quot;..
        /// </summary>
        public static string FirstRunFlavorText {
            get {
                return ResourceManager.GetString("FirstRunFlavorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started, please visit the Settings page to key in your MPD server&apos;s URL and port.
        ///Keep in mind Stylophone can send usage data to help diagnose bugs. 
        ///If you&apos;re not okay with this, you can disable telemetry in the Settings.
        ///Hope you enjoy using the application!  
        ///.
        /// </summary>
        public static string FirstRunText {
            get {
                return ResourceManager.GetString("FirstRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Stylophone!.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close all open folders.
        /// </summary>
        public static string FoldersCollapseAll {
            get {
                return ResourceManager.GetString("FoldersCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FoldersHeader {
            get {
                return ResourceManager.GetString("FoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string FoldersLoadingTreeItem {
            get {
                return ResourceManager.GetString("FoldersLoadingTreeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPD Filesystem.
        /// </summary>
        public static string FoldersRoot {
            get {
                return ResourceManager.GetString("FoldersRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string LibraryHeader {
            get {
                return ResourceManager.GetString("LibraryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string LibrarySearchPlaceholder {
            get {
                return ResourceManager.GetString("LibrarySearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Volume.
        /// </summary>
        public static string LocalVolumeHeader {
            get {
                return ResourceManager.GetString("LocalVolumeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoButtonText {
            get {
                return ResourceManager.GetString("NoButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to Playlist {0}!.
        /// </summary>
        public static string NotificationAddedToPlaylist {
            get {
                return ResourceManager.GetString("NotificationAddedToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to Queue!.
        /// </summary>
        public static string NotificationAddedToQueue {
            get {
                return ResourceManager.GetString("NotificationAddedToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album art cache has been deleted..
        /// </summary>
        public static string NotificationCacheDeleted {
            get {
                return ResourceManager.GetString("NotificationCacheDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is already being updated..
        /// </summary>
        public static string NotificationDbAlreadyUpdating {
            get {
                return ResourceManager.GetString("NotificationDbAlreadyUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database update started..
        /// </summary>
        public static string NotificationDbUpdateStarted {
            get {
                return ResourceManager.GetString("NotificationDbUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Track is currently playing..
        /// </summary>
        public static string NotificationNoTrackPlaying {
            get {
                return ResourceManager.GetString("NotificationNoTrackPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tracks loaded yet..
        /// </summary>
        public static string NotificationNoTracksLoaded {
            get {
                return ResourceManager.GetString("NotificationNoTracksLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now Playing {0}.
        /// </summary>
        public static string NotificationNowPlayingTrack {
            get {
                return ResourceManager.GetString("NotificationNowPlayingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Playlist has been removed..
        /// </summary>
        public static string NotificationPlaylistRemoved {
            get {
                return ResourceManager.GetString("NotificationPlaylistRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up Next:.
        /// </summary>
        public static string PlaybackUpNext {
            get {
                return ResourceManager.GetString("PlaybackUpNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        public static string PlaylistsHeader {
            get {
                return ResourceManager.GetString("PlaylistsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string QueueHeader {
            get {
                return ResourceManager.GetString("QueueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick some Songs.
        /// </summary>
        public static string RandomTracksHeader {
            get {
                return ResourceManager.GetString("RandomTracksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffling through your library....
        /// </summary>
        public static string RandomTracksInProgress {
            get {
                return ResourceManager.GetString("RandomTracksInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using Stylophone! Would you like to rate the app on the Store? 
        ///(We won&apos;t ask again. 🙏).
        /// </summary>
        public static string RateAppPromptText {
            get {
                return ResourceManager.GetString("RateAppPromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the Application.
        /// </summary>
        public static string RateAppPromptTitle {
            get {
                return ResourceManager.GetString("RateAppPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string SearchAlbumsToggle {
            get {
                return ResourceManager.GetString("SearchAlbumsToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artists.
        /// </summary>
        public static string SearchArtistsToggle {
            get {
                return ResourceManager.GetString("SearchArtistsToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for &quot;{0}&quot; on the server....
        /// </summary>
        public static string SearchGoToDetail {
            get {
                return ResourceManager.GetString("SearchGoToDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results have been found....
        /// </summary>
        public static string SearchNoResultsTitle_Text {
            get {
                return ResourceManager.GetString("SearchNoResultsTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Tracks....
        /// </summary>
        public static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results for &quot;{0}&quot;.
        /// </summary>
        public static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracks.
        /// </summary>
        public static string SearchTracksToggle {
            get {
                return ResourceManager.GetString("SearchTracksToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this application.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pretty cool MPD Client. Uses MpcNET..
        /// </summary>
        public static string SettingsAboutText {
            get {
                return ResourceManager.GetString("SettingsAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Album Art from the MPD Server.
        /// </summary>
        public static string SettingsAlbumArt {
            get {
                return ResourceManager.GetString("SettingsAlbumArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylophone stores album art locally to avoid overloading your MPD Server..
        /// </summary>
        public static string SettingsAlbumArtText {
            get {
                return ResourceManager.GetString("SettingsAlbumArtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string SettingsAnalytics {
            get {
                return ResourceManager.GetString("SettingsAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Stylophone to send crash and analytics reports.
        /// </summary>
        public static string SettingsAnalyticsText {
            get {
                return ResourceManager.GetString("SettingsAnalyticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting will apply after restarting the app..
        /// </summary>
        public static string SettingsApplyOnRestart {
            get {
                return ResourceManager.GetString("SettingsApplyOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Cache.
        /// </summary>
        public static string SettingsClearCache {
            get {
                return ResourceManager.GetString("SettingsClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the local album art cache.
        /// </summary>
        public static string SettingsClearCacheDescription {
            get {
                return ResourceManager.GetString("SettingsClearCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalization.
        /// </summary>
        public static string SettingsCustomization {
            get {
                return ResourceManager.GetString("SettingsCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database and Album Art.
        /// </summary>
        public static string SettingsDatabase {
            get {
                return ResourceManager.GetString("SettingsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Code, License and Privacy Statement.
        /// </summary>
        public static string SettingsGithub {
            get {
                return ResourceManager.GetString("SettingsGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Difegue/Stylophone.
        /// </summary>
        public static string SettingsGithubLink {
            get {
                return ResourceManager.GetString("SettingsGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Playback available.
        /// </summary>
        public static string SettingsLocalPlaybackAvailable {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Playback.
        /// </summary>
        public static string SettingsLocalPlaybackHeader {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream port.
        /// </summary>
        public static string SettingsLocalPlaybackPortHeader {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackPortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set this to the port of your server&apos;s httpd stream..
        /// </summary>
        public static string SettingsLocalPlaybackPortText {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackPortText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylophone can play your MPD Server&apos;s music stream.
        ///Enabling this option will show a second volume slider to control local volume..
        /// </summary>
        public static string SettingsLocalPlaybackText {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find an MPD server at this address!.
        /// </summary>
        public static string SettingsNoServerError {
            get {
                return ResourceManager.GetString("SettingsNoServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MPD Server.
        /// </summary>
        public static string SettingsServer {
            get {
                return ResourceManager.GetString("SettingsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname.
        /// </summary>
        public static string SettingsServerHost {
            get {
                return ResourceManager.GetString("SettingsServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SettingsServerPassword {
            get {
                return ResourceManager.GetString("SettingsServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string SettingsServerPort {
            get {
                return ResourceManager.GetString("SettingsServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System default.
        /// </summary>
        public static string SettingsThemeDefault {
            get {
                return ResourceManager.GetString("SettingsThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Density.
        /// </summary>
        public static string SettingsUIDensity {
            get {
                return ResourceManager.GetString("SettingsUIDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        public static string SettingsUIDensityCompact {
            get {
                return ResourceManager.GetString("SettingsUIDensityCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string SettingsUIDensityNormal {
            get {
                return ResourceManager.GetString("SettingsUIDensityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string SettingsUpdateDatabase {
            get {
                return ResourceManager.GetString("SettingsUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation might take the server some time to complete..
        /// </summary>
        public static string SettingsUpdateDbDesc {
            get {
                return ResourceManager.GetString("SettingsUpdateDbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the MPD Server Database.
        /// </summary>
        public static string SettingsUpdateDbTitle {
            get {
                return ResourceManager.GetString("SettingsUpdateDbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song playback.
        /// </summary>
        public static string SongPlaybackLabel {
            get {
                return ResourceManager.GetString("SongPlaybackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesButtonText {
            get {
                return ResourceManager.GetString("YesButtonText", resourceCulture);
            }
        }
    }
}
