//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylophone.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stylophone.Localization.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added to Playlist {0}!.
        /// </summary>
        public static string AddedToPlaylistText {
            get {
                return ResourceManager.GetString("AddedToPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added to Queue!.
        /// </summary>
        public static string AddedToQueueText {
            get {
                return ResourceManager.GetString("AddedToQueueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylophone.
        /// </summary>
        public static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylophone.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Album art cache has been deleted..
        /// </summary>
        public static string CacheDeletedText {
            get {
                return ResourceManager.GetString("CacheDeletedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t clear queue!.
        /// </summary>
        public static string CantClearError {
            get {
                return ResourceManager.GetString("CantClearError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database is already being updated..
        /// </summary>
        public static string DatabaseAlreadyUpdatingText {
            get {
                return ResourceManager.GetString("DatabaseAlreadyUpdatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database update started..
        /// </summary>
        public static string DatabaseUpdateStartedText {
            get {
                return ResourceManager.GetString("DatabaseUpdateStartedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Playlist?.
        /// </summary>
        public static string DeletePlaylistContentDialog {
            get {
                return ResourceManager.GetString("DeletePlaylistContentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t add Album: {0}.
        /// </summary>
        public static string ErrorAddingAlbum {
            get {
                return ResourceManager.GetString("ErrorAddingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t play content: {0}.
        /// </summary>
        public static string ErrorPlayingText {
            get {
                return ResourceManager.GetString("ErrorPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parameter must be an Enum name!.
        /// </summary>
        public static string ExceptionEnumToBooleanConverterParameterMustBeAnEnumName {
            get {
                return ResourceManager.GetString("ExceptionEnumToBooleanConverterParameterMustBeAnEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à value must be an Enum!.
        /// </summary>
        public static string ExceptionEnumToBooleanConverterValueMustBeAnEnum {
            get {
                return ResourceManager.GetString("ExceptionEnumToBooleanConverterValueMustBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name is null or empty. Specify a valid file name.
        /// </summary>
        public static string ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All pages opened in a new window must subscribe to the Released Event..
        /// </summary>
        public static string ExceptionViewLifeTimeControlMissingReleasedSubscription {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlMissingReleasedSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This view is being disposed..
        /// </summary>
        public static string ExceptionViewLifeTimeControlViewDisposal {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlViewDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folders.
        /// </summary>
        public static string FoldersHeader {
            get {
                return ResourceManager.GetString("FoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: {0}.
        /// </summary>
        public static string GenericErrorText {
            get {
                return ResourceManager.GetString("GenericErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search for &quot;{0}&quot; on the server....
        /// </summary>
        public static string GoToDetailSearch {
            get {
                return ResourceManager.GetString("GoToDetailSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid MPD Response..
        /// </summary>
        public static string InvalidMPDResponseError {
            get {
                return ResourceManager.GetString("InvalidMPDResponseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library.
        /// </summary>
        public static string LibraryHeader {
            get {
                return ResourceManager.GetString("LibraryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string LoadingTreeItem {
            get {
                return ResourceManager.GetString("LoadingTreeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This track doesn&apos;t have a matching Album..
        /// </summary>
        public static string NoAlbumErrorText {
            get {
                return ResourceManager.GetString("NoAlbumErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Track is currently playing..
        /// </summary>
        public static string NoTrackPlayingText {
            get {
                return ResourceManager.GetString("NoTrackPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Tracks found on Server..
        /// </summary>
        public static string NoTracksFound {
            get {
                return ResourceManager.GetString("NoTracksFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No tracks loaded yet..
        /// </summary>
        public static string NoTracksLoaded {
            get {
                return ResourceManager.GetString("NoTracksLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now Playing {0}.
        /// </summary>
        public static string NowPlayingText {
            get {
                return ResourceManager.GetString("NowPlayingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Playlist has been removed..
        /// </summary>
        public static string PlaylistRemovedText {
            get {
                return ResourceManager.GetString("PlaylistRemovedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queue.
        /// </summary>
        public static string QueueHeader {
            get {
                return ResourceManager.GetString("QueueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Results for &quot;{0}&quot;.
        /// </summary>
        public static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this application.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MPD Client for the Universal Windows Platform, based on MpcNET..
        /// </summary>
        public static string SettingsAboutText {
            get {
                return ResourceManager.GetString("SettingsAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analytics.
        /// </summary>
        public static string SettingsAnalytics {
            get {
                return ResourceManager.GetString("SettingsAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow Stylophone to send crash and analytics reports.
        /// </summary>
        public static string SettingsAnalyticsText {
            get {
                return ResourceManager.GetString("SettingsAnalyticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This setting will apply after restarting the app..
        /// </summary>
        public static string SettingsApplyOnRestart {
            get {
                return ResourceManager.GetString("SettingsApplyOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Cache.
        /// </summary>
        public static string SettingsClearCache {
            get {
                return ResourceManager.GetString("SettingsClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylophone stores album art locally to avoid overloading your MPD Server.
        ///If you want to clear the album art cache, click this button..
        /// </summary>
        public static string SettingsClearCacheDescription {
            get {
                return ResourceManager.GetString("SettingsClearCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personalization.
        /// </summary>
        public static string SettingsCustomization {
            get {
                return ResourceManager.GetString("SettingsCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database and Album Art.
        /// </summary>
        public static string SettingsDatabase {
            get {
                return ResourceManager.GetString("SettingsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Code, License and Privacy Statement.
        /// </summary>
        public static string SettingsGithub {
            get {
                return ResourceManager.GetString("SettingsGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/Difegue/Stylophone.
        /// </summary>
        public static string SettingsGithubLink {
            get {
                return ResourceManager.GetString("SettingsGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MPD Server.
        /// </summary>
        public static string SettingsServer {
            get {
                return ResourceManager.GetString("SettingsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hostname.
        /// </summary>
        public static string SettingsServerHost {
            get {
                return ResourceManager.GetString("SettingsServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        public static string SettingsServerPort {
            get {
                return ResourceManager.GetString("SettingsServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Windows default.
        /// </summary>
        public static string SettingsThemeDefault {
            get {
                return ResourceManager.GetString("SettingsThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UI Density.
        /// </summary>
        public static string SettingsUIDensity {
            get {
                return ResourceManager.GetString("SettingsUIDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact.
        /// </summary>
        public static string SettingsUIDensityCompact {
            get {
                return ResourceManager.GetString("SettingsUIDensityCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        public static string SettingsUIDensityNormal {
            get {
                return ResourceManager.GetString("SettingsUIDensityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Server Database.
        /// </summary>
        public static string SettingsUpdateDatabase {
            get {
                return ResourceManager.GetString("SettingsUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This operation might take the server some time to complete..
        /// </summary>
        public static string UpdateDbDialogText {
            get {
                return ResourceManager.GetString("UpdateDbDialogText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update the Server Database?.
        /// </summary>
        public static string UpdateDbDialogTitle {
            get {
                return ResourceManager.GetString("UpdateDbDialogTitle", resourceCulture);
            }
        }
    }
}
