//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylophone.Localization.Strings {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stylophone.Localization.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change Volume.
        /// </summary>
        public static string ActionChangeVolume {
            get {
                return ResourceManager.GetString("ActionChangeVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Mini Player.
        /// </summary>
        public static string ActionCompactOverlay {
            get {
                return ResourceManager.GetString("ActionCompactOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à More Actions.
        /// </summary>
        public static string ActionMore {
            get {
                return ResourceManager.GetString("ActionMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play/Pause.
        /// </summary>
        public static string ActionPlayPause {
            get {
                return ResourceManager.GetString("ActionPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Next Track.
        /// </summary>
        public static string ActionSkipNext {
            get {
                return ResourceManager.GetString("ActionSkipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Previous Track.
        /// </summary>
        public static string ActionSkipPrevious {
            get {
                return ResourceManager.GetString("ActionSkipPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Repeat.
        /// </summary>
        public static string ActionToggleRepeat {
            get {
                return ResourceManager.GetString("ActionToggleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Toggle Shuffle.
        /// </summary>
        public static string ActionToggleShuffle {
            get {
                return ResourceManager.GetString("ActionToggleShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create New Playlist.
        /// </summary>
        public static string AddToPlaylistCreateNewPlaylist {
            get {
                return ResourceManager.GetString("AddToPlaylistCreateNewPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Playlist Name.
        /// </summary>
        public static string AddToPlaylistNewPlaylistName {
            get {
                return ResourceManager.GetString("AddToPlaylistNewPlaylistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select a Playlist.
        /// </summary>
        public static string AddToPlaylistPlaceholder {
            get {
                return ResourceManager.GetString("AddToPlaylistPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string AddToPlaylistPrimaryButtonText {
            get {
                return ResourceManager.GetString("AddToPlaylistPrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add track(s) to the following Playlist:.
        /// </summary>
        public static string AddToPlaylistText {
            get {
                return ResourceManager.GetString("AddToPlaylistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to Playlist.
        /// </summary>
        public static string AddToPlaylistTitle {
            get {
                return ResourceManager.GetString("AddToPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylophone.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save Queue as Playlist.
        /// </summary>
        public static string ContextMenuAddQueueToPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuAddQueueToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to Playlist.
        /// </summary>
        public static string ContextMenuAddToPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add to Queue.
        /// </summary>
        public static string ContextMenuAddToQueue {
            get {
                return ResourceManager.GetString("ContextMenuAddToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Queue.
        /// </summary>
        public static string ContextMenuClearQueue {
            get {
                return ResourceManager.GetString("ContextMenuClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Playlist.
        /// </summary>
        public static string ContextMenuDeletePlaylist {
            get {
                return ResourceManager.GetString("ContextMenuDeletePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        public static string ContextMenuPlay {
            get {
                return ResourceManager.GetString("ContextMenuPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove from Playlist.
        /// </summary>
        public static string ContextMenuRemoveFromPlaylist {
            get {
                return ResourceManager.GetString("ContextMenuRemoveFromPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remove from Queue.
        /// </summary>
        public static string ContextMenuRemoveFromQueue {
            get {
                return ResourceManager.GetString("ContextMenuRemoveFromQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View Album.
        /// </summary>
        public static string ContextMenuViewAlbum {
            get {
                return ResourceManager.GetString("ContextMenuViewAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Playlist?.
        /// </summary>
        public static string DeletePlaylistContentDialog {
            get {
                return ResourceManager.GetString("DeletePlaylistContentDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Is your MPD server connected?.
        /// </summary>
        public static string EmptyFoldersDesc {
            get {
                return ResourceManager.GetString("EmptyFoldersDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No folders found on server..
        /// </summary>
        public static string EmptyFoldersTitle {
            get {
                return ResourceManager.GetString("EmptyFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ain&apos;t nothin&apos; like an empty library..
        /// </summary>
        public static string EmptyLibraryTitle {
            get {
                return ResourceManager.GetString("EmptyLibraryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Get some tracks in there!.
        /// </summary>
        public static string EmptyPlaylistDesc {
            get {
                return ResourceManager.GetString("EmptyPlaylistDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à I can&apos;t jam to this..
        /// </summary>
        public static string EmptyPlaylistTitle {
            get {
                return ResourceManager.GetString("EmptyPlaylistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Why don&apos;t you add some music?.
        /// </summary>
        public static string EmptyQueueDesc {
            get {
                return ResourceManager.GetString("EmptyQueueDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All is quiet now..
        /// </summary>
        public static string EmptyQueueTitle {
            get {
                return ResourceManager.GetString("EmptyQueueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Tracks found on Server..
        /// </summary>
        public static string EmptySearchDesc {
            get {
                return ResourceManager.GetString("EmptySearchDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Funky Fresh Search!.
        /// </summary>
        public static string EmptySearchTitle {
            get {
                return ResourceManager.GetString("EmptySearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t add Album: {0}.
        /// </summary>
        public static string ErrorAddingAlbum {
            get {
                return ResourceManager.GetString("ErrorAddingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t clear queue!.
        /// </summary>
        public static string ErrorCantClearCache {
            get {
                return ResourceManager.GetString("ErrorCantClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error: {0}.
        /// </summary>
        public static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid MPD Response..
        /// </summary>
        public static string ErrorInvalidMPDResponse {
            get {
                return ResourceManager.GetString("ErrorInvalidMPDResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This track doesn&apos;t have a matching Album..
        /// </summary>
        public static string ErrorNoMatchingAlbum {
            get {
                return ResourceManager.GetString("ErrorNoMatchingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid password.
        /// </summary>
        public static string ErrorPassword {
            get {
                return ResourceManager.GetString("ErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t play content: {0}.
        /// </summary>
        public static string ErrorPlayingTrack {
            get {
                return ResourceManager.GetString("ErrorPlayingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parameter must be an Enum name!.
        /// </summary>
        public static string ExceptionEnumToBooleanConverterParameterMustBeAnEnumName {
            get {
                return ResourceManager.GetString("ExceptionEnumToBooleanConverterParameterMustBeAnEnumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à value must be an Enum!.
        /// </summary>
        public static string ExceptionEnumToBooleanConverterValueMustBeAnEnum {
            get {
                return ResourceManager.GetString("ExceptionEnumToBooleanConverterValueMustBeAnEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File name is null or empty. Specify a valid file name.
        /// </summary>
        public static string ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionSettingsStorageExtensionsFileNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All pages opened in a new window must subscribe to the Released Event..
        /// </summary>
        public static string ExceptionViewLifeTimeControlMissingReleasedSubscription {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlMissingReleasedSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This view is being disposed..
        /// </summary>
        public static string ExceptionViewLifeTimeControlViewDisposal {
            get {
                return ResourceManager.GetString("ExceptionViewLifeTimeControlViewDisposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To get started, please visit the Settings page to key in your MPD server&apos;s URL and port.
        ///Hope you enjoy using the application!.
        /// </summary>
        public static string FirstRunText {
            get {
                return ResourceManager.GetString("FirstRunText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to Stylophone!.
        /// </summary>
        public static string FirstRunTitle {
            get {
                return ResourceManager.GetString("FirstRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close all open folders.
        /// </summary>
        public static string FoldersCollapseAll {
            get {
                return ResourceManager.GetString("FoldersCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Folders.
        /// </summary>
        public static string FoldersHeader {
            get {
                return ResourceManager.GetString("FoldersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Loading....
        /// </summary>
        public static string FoldersLoadingTreeItem {
            get {
                return ResourceManager.GetString("FoldersLoadingTreeItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MPD Filesystem.
        /// </summary>
        public static string FoldersRoot {
            get {
                return ResourceManager.GetString("FoldersRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Library.
        /// </summary>
        public static string LibraryHeader {
            get {
                return ResourceManager.GetString("LibraryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string LibrarySearchPlaceholder {
            get {
                return ResourceManager.GetString("LibrarySearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added to Playlist {0}!.
        /// </summary>
        public static string NotificationAddedToPlaylist {
            get {
                return ResourceManager.GetString("NotificationAddedToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added to Queue!.
        /// </summary>
        public static string NotificationAddedToQueue {
            get {
                return ResourceManager.GetString("NotificationAddedToQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Album art cache has been deleted..
        /// </summary>
        public static string NotificationCacheDeleted {
            get {
                return ResourceManager.GetString("NotificationCacheDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The database is already being updated..
        /// </summary>
        public static string NotificationDbAlreadyUpdating {
            get {
                return ResourceManager.GetString("NotificationDbAlreadyUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database update started..
        /// </summary>
        public static string NotificationDbUpdateStarted {
            get {
                return ResourceManager.GetString("NotificationDbUpdateStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Track is currently playing..
        /// </summary>
        public static string NotificationNoTrackPlaying {
            get {
                return ResourceManager.GetString("NotificationNoTrackPlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No tracks loaded yet..
        /// </summary>
        public static string NotificationNoTracksLoaded {
            get {
                return ResourceManager.GetString("NotificationNoTracksLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Now Playing {0}.
        /// </summary>
        public static string NotificationNowPlayingTrack {
            get {
                return ResourceManager.GetString("NotificationNowPlayingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The Playlist has been removed..
        /// </summary>
        public static string NotificationPlaylistRemoved {
            get {
                return ResourceManager.GetString("NotificationPlaylistRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Off.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string OKButtonText {
            get {
                return ResourceManager.GetString("OKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à On.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Up Next:.
        /// </summary>
        public static string PlaybackUpNext {
            get {
                return ResourceManager.GetString("PlaybackUpNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Playlists.
        /// </summary>
        public static string PlaylistsHeader {
            get {
                return ResourceManager.GetString("PlaylistsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Queue.
        /// </summary>
        public static string QueueHeader {
            get {
                return ResourceManager.GetString("QueueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Albums.
        /// </summary>
        public static string SearchAlbumsToggle {
            get {
                return ResourceManager.GetString("SearchAlbumsToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Artists.
        /// </summary>
        public static string SearchArtistsToggle {
            get {
                return ResourceManager.GetString("SearchArtistsToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search for &quot;{0}&quot; on the server....
        /// </summary>
        public static string SearchGoToDetail {
            get {
                return ResourceManager.GetString("SearchGoToDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Results have been found....
        /// </summary>
        public static string SearchNoResultsTitle_Text {
            get {
                return ResourceManager.GetString("SearchNoResultsTitle.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Tracks....
        /// </summary>
        public static string SearchPlaceholderText {
            get {
                return ResourceManager.GetString("SearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search Results for &quot;{0}&quot;.
        /// </summary>
        public static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tracks.
        /// </summary>
        public static string SearchTracksToggle {
            get {
                return ResourceManager.GetString("SearchTracksToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About this application.
        /// </summary>
        public static string SettingsAbout {
            get {
                return ResourceManager.GetString("SettingsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MPD Client for the Universal Windows Platform, based on MpcNET..
        /// </summary>
        public static string SettingsAboutText {
            get {
                return ResourceManager.GetString("SettingsAboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analytics.
        /// </summary>
        public static string SettingsAnalytics {
            get {
                return ResourceManager.GetString("SettingsAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow Stylophone to send crash and analytics reports.
        /// </summary>
        public static string SettingsAnalyticsText {
            get {
                return ResourceManager.GetString("SettingsAnalyticsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This setting will apply after restarting the app..
        /// </summary>
        public static string SettingsApplyOnRestart {
            get {
                return ResourceManager.GetString("SettingsApplyOnRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear Cache.
        /// </summary>
        public static string SettingsClearCache {
            get {
                return ResourceManager.GetString("SettingsClearCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stylophone stores album art locally to avoid overloading your MPD Server.
        ///If you want to clear the album art cache, click this button..
        /// </summary>
        public static string SettingsClearCacheDescription {
            get {
                return ResourceManager.GetString("SettingsClearCacheDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Personalization.
        /// </summary>
        public static string SettingsCustomization {
            get {
                return ResourceManager.GetString("SettingsCustomization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Database and Album Art.
        /// </summary>
        public static string SettingsDatabase {
            get {
                return ResourceManager.GetString("SettingsDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Source Code, License and Privacy Statement.
        /// </summary>
        public static string SettingsGithub {
            get {
                return ResourceManager.GetString("SettingsGithub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/Difegue/Stylophone.
        /// </summary>
        public static string SettingsGithubLink {
            get {
                return ResourceManager.GetString("SettingsGithubLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local Playback available.
        /// </summary>
        public static string SettingsLocalPlaybackAvailable {
            get {
                return ResourceManager.GetString("SettingsLocalPlaybackAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couldn&apos;t find an MPD server at this address!.
        /// </summary>
        public static string SettingsNoServerError {
            get {
                return ResourceManager.GetString("SettingsNoServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MPD Server.
        /// </summary>
        public static string SettingsServer {
            get {
                return ResourceManager.GetString("SettingsServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hostname.
        /// </summary>
        public static string SettingsServerHost {
            get {
                return ResourceManager.GetString("SettingsServerHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string SettingsServerPassword {
            get {
                return ResourceManager.GetString("SettingsServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        public static string SettingsServerPort {
            get {
                return ResourceManager.GetString("SettingsServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Theme.
        /// </summary>
        public static string SettingsTheme {
            get {
                return ResourceManager.GetString("SettingsTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dark.
        /// </summary>
        public static string SettingsThemeDark {
            get {
                return ResourceManager.GetString("SettingsThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à System default.
        /// </summary>
        public static string SettingsThemeDefault {
            get {
                return ResourceManager.GetString("SettingsThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Light.
        /// </summary>
        public static string SettingsThemeLight {
            get {
                return ResourceManager.GetString("SettingsThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à UI Density.
        /// </summary>
        public static string SettingsUIDensity {
            get {
                return ResourceManager.GetString("SettingsUIDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compact.
        /// </summary>
        public static string SettingsUIDensityCompact {
            get {
                return ResourceManager.GetString("SettingsUIDensityCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Normal.
        /// </summary>
        public static string SettingsUIDensityNormal {
            get {
                return ResourceManager.GetString("SettingsUIDensityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update Server Database.
        /// </summary>
        public static string SettingsUpdateDatabase {
            get {
                return ResourceManager.GetString("SettingsUpdateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This operation might take the server some time to complete..
        /// </summary>
        public static string SettingsUpdateDbDesc {
            get {
                return ResourceManager.GetString("SettingsUpdateDbDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update the MPD Server Database.
        /// </summary>
        public static string SettingsUpdateDbTitle {
            get {
                return ResourceManager.GetString("SettingsUpdateDbTitle", resourceCulture);
            }
        }
    }
}
